Setup Backend Rails
bruk19/hello-rails-back-end pull request #1
Opened 2022-11-03 08:07 UTC by bruk19

2022-11-03 12:46 UTC, GzimAsani requested changes
### Hello  @bruk19                 :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with creating a store correctly :+1:  :+1: 

 ## Required Changes 
### Frontend part:
- [ ] The router should be present on your `app.js` file where will be the `greetings` component
- [ ] Update the imports they are throwing errors
![image](https://user-images.githubusercontent.com/62705947/199722934-399a39ac-6a1b-4991-9e0a-28bb60c662c0.png)
- [ ] The greetings are not coming on the front-end because of the problems on the backend. Hint: the greetings should be shown on the page on the front-end
- [ ] Good job displaying the link to front-end from your back-end readme file. But you should also display the link to the back-end from the front-end readme file
### Back-end
- [ ] Check the comments below :arrow_double_down: 






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 12:46 UTC, GzimAsani commented on config/database.yml
> +  adapter: sqlite3
- [ ] You need to use `Postgres` as your database

2022-11-03 12:46 UTC, GzimAsani commented on db/seeds.rb
> +#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
- [ ] You need to create a database table for storing different greetings was created

2022-11-03 12:46 UTC, GzimAsani commented on app/models/application_record.rb
> +end
- [ ] You need to create a model for your greetings

2022-11-03 12:46 UTC, GzimAsani commented on app/controllers/api/v1/greetings_controller.rb
> +        render json: { status: 'SUCCESS', message: 'Loaded messages', greeting: }, status: :ok
- [ ] I am getting back an error when trying to check your greetings 
![image](https://user-images.githubusercontent.com/62705947/199722189-1557a834-b1c2-491f-9d27-ee6cf727d367.png)

2022-11-04 06:27 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @bruk19      , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x] Your project is professional 

- [x]  Your repo is professional 




 

- [x] No Linter Errors





Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-04 06:37 UTC, merged